### ISSUE TITLE
Destroying vehicle

### ISSUE THREAD

**Issue by asdat3** [McWulf1991/plugin-core-tuningshop#1]
after clicking the buy option this happens always with my vehilce
even If I change nothing in the stance section and only in the options section
![Capture](https://user-images.githubusercontent.com/29544382/181725313-5c73b1c1-7ff3-49f4-b130-c77ce0e7c133.PNG)

**Comment by McWulf1991** [comment]
Did you create a new instance after each try to modify? (Restart the server) Did you adjust any values after entering the tuning shop? I didn't mentioned it, but there are no "safeoptions", so you have to figure out yourself. Also i didn't implement any savings to the database, so your car doesn't get saved after pressing the buy button. So yor car should reset after a server restart. You have to restart the server and your car should be fine.

**Comment by asdat3** [comment]
no
yes
okay well then this plugin is pretty useless for me sorry
